src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
Hello, I’m using Openfire 4.2.3 with REST API plugin 1.3.9 and two nodes hazelcast cluster (plugin 2.4.2).
I found unexpected behavior of `PUT /plugins/restapi/v1/chatrooms/{roomName}` API. When I send the HTTP request, one cluster node that received the HTTP request has room occuoants without change but the other node has no occupants unexpectedly.
See details: https://discourse.igniterealtime.org/t/rest-api-and-multi-node-hazelcast-cluster-all-room-members-kicked-out-unexpectedly/85060
---
My commit info:
I removed `CacheFactory.doClusterTask(new RoomAvailableEvent((LocalMUCRoom) room)) ` with following reason.
- `MUCRoomController` is not responsible for room creation and `RoomAvailableEvent` is called in `mucService.getChatRoom` method.
- `RoomAvailableEvent` calls …
=> fix: room occupants of remote nodes kicked out unexpectedly in cluster env

src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/OccupantEntity.java
Had a situation where we needed the User Address JID instead of the MUC JID, creating a PR because others may find this a useful addition.
=> Add User Address when getting room occupants.

src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
I found that room occupants are always kicked out when `PUT /chatrooms/{roomName}` is executed even if the room affiliations are not changed.
It's better to keep occupants if the room affiliations are not changed. Because clients have to re-join to room if kicked out and it causes complexity.
=> Check difference between room affiliations and MUCRoomEntity affiliations to avoid redundant occupant kickouts

pom.xml, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/java/org/jivesoftware/openfire/plugin/rest/utils/MUCRoomUtils.java
Openfire released a breaking change in version 4.6 by changing the signature of the `MUCRoom.send` function. 
Therefore this plugin does not work properly with Openfire >= 4.6.0.
This pull request attempts to restore compatibility with the current Openfire versions.
~~I don't know if you can release a new version for that, because this will of course break the plugin for all the older Openfire versions, but I thought I'd share my 4.6-compatible fork anyway.~~
=> Openfire 4.6 Compatibility

src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
To reproduce this NPE at runtime may require having a broken OF v4.6.x installation, since I saw this NPE being thrown while investigating breakage in v4.6.3. There's no unit test to show how this affects expectations.
Anyways this should return the same result logically, but avoid NPE, if input parameters are null or if parameter data-contents contain null.
=> avoid NPE in MucRoomController#equalToAffiliations

changelog.html, plugin.xml, pom.xml, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/java/org/jivesoftware/openfire/plugin/rest/utils/MUCRoomUtils.java
Openfire 4.6.1 introduced an API change that made older versions of the restAPI plugin incompatible.
This commit increased the dependency of Openfire to version 4.6.1, which will resolve exceptions that report ` org.jivesoftware.openfire.muc.MUCRole$Role cannot be cast to java.lang.String`
=> fixes #56: Bump Openfire dependency to 4.6.1

changelog.html, pom.xml
`mvn verify -P deps` will create a report in the target directory called `dependency-check-report.html`, reporting on any dependencies, direct or down the chain, with known CVEs.
Fixes #77
=> Add dependency check report

changelog.html, readme.html, readme.md, src/java/org/jivesoftware/openfire/plugin/rest/controller/GroupController.java, src/java/org/jivesoftware/openfire/plugin/rest/controller/UserServiceLegacyController.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/GroupEntity.java
Roster sharing is an optional parameter of creating/updating a group, but when not provided is assumed to be false.
Could be a breaking change for some users.
=> Fix #52 by setting group roster sharing to false by default

changelog.html, plugin.xml, src/java/org/jivesoftware/openfire/plugin/rest/CustomJacksonMapperProvider.java, src/java/org/jivesoftware/openfire/plugin/rest/service/JerseyWrapper.java
Jackson's objectmapper is now configured to prefer the JAXB annotations for serialization.
=> fixes #79: Ensure consistent JSON representation

changelog.html, src/java/org/jivesoftware/openfire/plugin/rest/RESTServicePlugin.java
Prior to this, only user-defined properties were exposed.
=> fixes #80: Expose all system properties

changelog.html, src/java/org/jivesoftware/openfire/plugin/rest/CustomJacksonMapperProvider.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/OccupantEntity.java
Prior to release 1.7.0, the JSON representation of entities did not include fields that hold null values.
Also, where both JAXB XmlElementWrapper and XmlElement annotations are used, the existing config will use the JAXB XmlElementWrapper annotation for JSON serialization, which hold a value that causes the resulting JSON value to be different from earlier versions. To make sure the correct value is used, this commit ensures that Jackson annotations are preferred over JAXB annotations. As long as Jackson annotations are present, the correct result will be generated.
Ideally, this PR is rebased on top of https://github.com/igniterealtime/openfire-restAPI-plugin/pull/89 or the other way around (which should add tests that verify the expected behavior).
=> fixes #88: JSON serialization configuration changes

pom.xml, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/java/org/jivesoftware/openfire/plugin/rest/controller/UserServiceController.java, src/test/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomMembersServiceBackwardCompatibilityTest.java, src/test/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomServiceBackwardCompatibilityTest.java, src/test/java/org/jivesoftware/openfire/plugin/rest/service/UserRosterServiceBackwardCompatibilityTest.java
Users of the plugin benefit from a stable API: subtle changes to the input our output of the services can break third-party applications that depend on this API.
To help ensure that the API does not change, this commit introduces a set of Unit tests that verify the input and output of service calls, by comparing them against known-good values (collected in the past).
This is far from a finished PR (hence the 'draft' status). I'm looking for feedback on the approach.
=> Add tests to check for backwards compatibility

changelog.html, plugin.xml, pom.xml
I'd like to not wait to long to push out 1.7.1. As this release fixes backwards compatibility issues introduced in 1.7.0, I'm eager to make 1.7.0 no longer be the last release (and thus try to minimize the amount of people that adopt to the syntax in that version.
This PR should be rebased/merged, but _not_ squashed. A release should be drafted on the first commit of this PR.
=> Release 1.7.1

changelog.html, src/java/org/jivesoftware/openfire/plugin/rest/RESTServicePlugin.java, src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java, src/java/org/jivesoftware/openfire/plugin/rest/service/JerseyWrapper.java, src/java/org/jivesoftware/openfire/plugin/rest/service/RestAPIService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/SystemService.java
Adds endpoints that perform checks for 'readiness' of Openfire (to accept data), and 'liveness' (to check if Openfire is in a state where it needs a reboot). See issue #92 for more details.
An endpoint is added for each individual check. Additionally, and endpoint has also been added that performs all checks of a particular type.
=> fixes #92: add endpoints for readiness and liveness checks

readme.html
The HTML version of the readme was seriously lagging behind the Markdown version. This commit brings both back in sync.
To generate the HTML version, I took the Markdown version, which I added to the webapp of https://stackedit.io/
Next, I exported the stackedit-generated page as HTML, using their "Stylized HTML with TOC" template.
I've only changed the HTML title in the generated file.
=> Regenerated readme.html from readme.md

changelog.html, src/java/org/jivesoftware/openfire/plugin/rest/AuthFilter.java
Fixes #96
Tested via /plugins/restapi/docs/index.html#/System/liveness and the like.
=> fixes #96: Don't require auth for readiness/liveness endpoints

changelog.html, src/web/docs/index.html
Fixes #99 - the link to the openapi.yml below the title was hardcoded to localhost.
becomes
/hattip @ruicaramalho for the report
=> fixes #99: Don't hard-code OpenAPI yaml link to localhost

changelog.html, plugin.xml, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/java/org/jivesoftware/openfire/plugin/rest/exceptions/ExceptionType.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomAdminsService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomMembersService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomOutcastsService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomOwnersService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomService.java
When requests are made against MUC services or rooms that do not exist (but are expected to), then the old implementation would return a HTTP 500 "Internal Server Error" response.
This commit explicitly checks if the MUC service/room that is used in the request exist, and return HTTP 404 "Not Found" when that's not the case.
I've also included more annotations that will cause Swagger to generate a more complete list of errors that are returned for MUC services.
this fixes #74
=> Properly process requests that have invalid MUC service or room references

changelog.html, plugin.xml, src/java/org/jivesoftware/openfire/plugin/rest/exceptions/RESTExceptionMapper.java
When the plugin is returning an error, this is likely caused by user input, and not by an implementation issue in Openfire or the plugin. Lets not log to `error`.
=> fixes #102: Reduce log level of error responses

changelog.html, plugin.xml, readme.html, readme.md, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/AdminEntities.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/MemberEntities.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/OutcastEntities.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/OwnerEntities.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomAdminsService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomMembersService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomOutcastsService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomOwnersService.java
This adds three new types of endpoints:
1. return all JIDs that have a particular affiliation to a particular chatroom:
`GET /restapi/v1/chatrooms/{room}/{affiliation}?servicename=conference`
2. replace all JIDs that have a particular affiliation to a particular chatroom:
`PUT /restapi/v1/chatrooms/{room}/{affiliation}?servicename=conference`
3. add multiplple JIDs with a particular affilaition to a particular chatroom:
`POST /restapi/v1/chatrooms/{room}/{affiliation}?servicename=conference`
This should make it a lot easier to make bulk operations. Prior to this commit, changes had to be applied one-by-one.
=> fixes #105: New endpoints for bulk operations of MUC room affiliations

changelog.html, plugin.xml, src/java/org/jivesoftware/openfire/plugin/rest/exceptions/RESTExceptionMapper.java
A HEAD request can be performed to check if an entity exists. If the answer is 'no' (represented by a 404 status code), then this should not be logged on a level that automatically gets written to a log file. This prevents cluttering of the log file.
=> fixes 108: Do not verbosely log non-existence of entity when performing HEAD request

changelog.html, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
When clustering, the MUC goes into the cache, but doesn't get an ID, and the savedToDB value is incorrect. No idea if this has any real world impact, but it's certainly wrong. This forces a sync the same way that Admin does when it creates a room.
Could this be #30?
=> Update cache when creating or updating MUCs

changelog.html, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
Fixes #113.
Switches the controller for the chatrooms endpoint to search on both name and naturalName, and makes the check for each to be case insensitive.
=> fixes 113: include naturalName in MUC search and make case insensitive

changelog.html, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
The fix for #113 didn't account for calling the endpoint without a search term, preventing the full list of rooms from being retrieved.
This switches some logic around to account for both search and non-search cases.
Looked at why the current tests didn't catch it, but those are service tests that rely on controller mocks. Any attempt to expand the tests now would orders of magnitude more effort than this fix is alone.
=> fixes 118: Return full room list from /chatrooms when not searching

.dependency-check-suppressions.xml, changelog.html, pom.xml
Solves some deps with open CVEs (and updates some other deps that don't).
Dependency Check is back to just Jetty complaints.
=> Dependency Updates

changelog.html, readme.md, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/RoomCreationResultEntities.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/RoomCreationResultEntity.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/RoomsCreationResult.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomService.java
New endpoint to create multiple chatrooms in one go. Fixes #127.
=> Create multiple chat rooms in one request

changelog.html, readme.md, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCServiceController.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/MUCServiceEntities.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/MUCServiceEntity.java, src/java/org/jivesoftware/openfire/plugin/rest/service/JerseyWrapper.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCServiceService.java
New endpoint to list chat services and create a new one. Fixes #130.
=> Create new chat service

changelog.html, readme.md, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/MUCInvitationEntity.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomAdminsService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomMembersService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomOutcastsService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomOwnersService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomService.java, src/java/org/jivesoftware/openfire/plugin/rest/utils/UserUtils.java
This PR adds functionality for sending invitations to users and groups. In two distinct ways: whenever a mutation is performed that causes new affiliations to exist, and explicitly by calling a specialised endpoint to send invitation messages.
Sending invitations is always optional, and the default is to not send any invitations.
Fixes #128.
Fixes #129.
=> Send invitations to users and groups

changelog.html, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
Prior to this commit, affiliation-groups (memberGroups, adminGroups, ownerGroups and outcastGroups) that were present in MUC room entities used to create up update a MUC room, were ignored.
=> fixes #136: Implement group role handling when creating/updating a room

changelog.html, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/MUCInvitationEntity.java, src/java/org/jivesoftware/openfire/plugin/rest/entity/MUCInvitationsEntity.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomAffiliationsService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomService.java
The fix for issue #141 introduces a template to replace four distinct URL patterns:
- `/restapi/v1/chatrooms/{roomName}/owners`
- `/restapi/v1/chatrooms/{roomName}/admins`
- `/restapi/v1/chatrooms/{roomName}/members`
- `/restapi/v1/chatrooms/{roomName}/outcasts`
got replaced by
- `/restapi/v1/chatrooms/{roomName}/{affiliation}`
Sadly, this template matches more than just those four. URLs like these also get caught, making them misbehave:
- `/restapi/v1/chatrooms/{roomName}/chathistory`
- `/restapi/v1/chatrooms/{roomName}/occupants`
- `/restapi/v1/chatrooms/{roomName}/participants`
- `/restapi/v1/chatrooms/{roomName}/invite`
This commit fixes the problem by applying a regular expression to the `{affiliation}` template, requiring it to match one of four distinct options.
Also introduces a …
=> fixes #146: Limit URI template match for MUC affiliation

src/java/org/jivesoftware/openfire/plugin/rest/RESTServicePlugin.java
The instance is unused, but isn't cleaned up with the lifecycle of the plugin. This can prevent the plugin's class loader from being completely destroyed when the plugin is unloaded/reloaded.
=> fixes #153: Remove unused static instance of RESTServicePlugin

src/i18n/restapi_i18n.properties, src/java/org/jivesoftware/openfire/plugin/rest/RESTServicePlugin.java, src/java/org/jivesoftware/openfire/plugin/rest/StatisticsFilter.java, src/java/org/jivesoftware/openfire/plugin/rest/service/JerseyWrapper.java
This commit adds statistics for every response generated in response to a HTTP request on one of the REST API endpoints.
The statistics show the amount of responses for each particular 'family' of status codes (1xx, 2xx, 3xx, 4xx and 5xx).
The Monitoring plugin can be used to review graphs of this data. Note that the current latest release of the Monitoring plugin (2.3.1) has an issue that affects the functionality when a plugin that _provides_ a statistic is unloaded/reloaded. See https://github.com/igniterealtime/openfire-monitoring-plugin/issues/238 for details. It is recommended to use this commit only in combination with a version of the Monitoring plugin in which this issue is fixed. A work-around for the issue, if it does occur, is to restart Openfire after a plugin has been …
=> fixes #155: Add statistics for endpoint responses

changelog.html, plugin.xml, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
Issues pop up when an attempt is ade to affiliate a JID more than once, especially when that JID is also an owner. Affiliating such a JID as something else will remove the ownership affiliation. This can trigger an issue where the room has no owners.
This commit introduces a check to verify that the inbound request does not define multiple affiliations for the same JID. It also reworks the way in which affiliations are applied.
=> fixes #159: Ensure that a JID can be affiliated only once

changelog.html, plugin.xml, pom.xml
Do not squash commits, as the first commit needs to be tagged as the release.
=> Release 1.10.1

changelog.html, plugin.xml, src/i18n/restapi_i18n.properties, src/i18n/restapi_i18n_nl.properties, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
Since Openfire 4.7.0, a new API is available that ensures that MUC data is synchronized across Openfire cluster nodes. This commit adds support for this API.
As a result, data consistency with regards to MUC-related data (chatrooms, mostly), should improve.
This commit contains two related changes:
- Invocation of `service.syncChatRoom()` after room changes, to ensure that those changes are visible to other cluste nodes.
- Application of room-specific mutexes when rooms are interacted with.
The addition of an additional mutex typically comes with a risk of introducing a deadlock-like scenario. As a mitigation for this, a new property has been introduced that controls if the mutex is engaged when the REST API interacts with MUC rooms.
The property name is …
=> fixes #188: Fix for clustering data consistency issue with MUC rooms

changelog.html, src/java/org/jivesoftware/openfire/plugin/rest/service/UserService.java
fixed: Support update user on Swagger.
=> fixed: Support update user on Swagger.

changelog.html, plugin.xml, pom.xml, src/java/org/jivesoftware/openfire/plugin/rest/controller/GroupController.java, src/java/org/jivesoftware/openfire/plugin/rest/controller/JustMarriedController.java, src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java, src/java/org/jivesoftware/openfire/plugin/rest/controller/UserServiceLegacyController.java
A couple of minor fixes to allow the Rest-API plugin to correctly work in Openfire 4.8.1.
The current version 1.10.2 is working fine with the new Openfire release, except for a method signature `org.jivesoftware.openfire.session.Session.getStatus()` that is used in 
`org.jivesoftware.openfire.plugin.rest.controller.SessionController.convertToSessionEntities(Collection<ClientSession> clientSessions):133`. (It expects the method to return an integer).
The current method usage is retrocompatible, however it is has to be built with the new Openfire sources of version 4.8.1. This of course brings some compilation problems with a couple of changes in the 4.8.1 code.
The following fixes will just allow for the plugin to work as expected without breaking things up, but are not to be considered …
=> Fixed dependencies errors for Openfire 4.8.1

changelog.html, plugin.xml, src/java/org/jivesoftware/openfire/plugin/rest/controller/SessionController.java
This replaces API of Openfire that was removed in Openfire 4.9.0. The plugin remains compatible with Openfire 4.8.0 and later.
Fixes #200
=> Fixes compatibility issue with Openfire 4.9.0

changelog.html, plugin.xml, pom.xml, src/java/org/jivesoftware/openfire/plugin/rest/AuthFilter.java, src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomAffiliationsService.java, src/java/org/jivesoftware/openfire/plugin/rest/service/UserServiceLegacy.java, src/java/org/jivesoftware/openfire/plugin/rest/utils/MUCRoomUtils.java, src/web/rest-api.jsp
Compatible with Openfire 5.0.0.
=> Compatible with Openfire 5.0.0.

changelog.html, plugin.xml, pom.xml, readme.html, readme.md, src/java/org/jivesoftware/openfire/plugin/rest/controller/UserServiceController.java, src/java/org/jivesoftware/openfire/plugin/rest/service/JerseyWrapper.java, src/java/org/jivesoftware/openfire/plugin/rest/service/UserVCardService.java
To generate the HTML version, I took the Markdown version, which I added to the webapp of https://stackedit.io/
Next, I exported the stackedit-generated page as HTML, using their "Stylized HTML with TOC" template.
I've only changed the HTML title in the generated file.
=> fixes #7: Add support for vCards
